services:
  mongo:
    image: mongo:6
    restart: unless-stopped
    ports:
      - "27017:27017"

  redis:
    image: redis:7
    restart: unless-stopped
    ports:
      - "6379:6379"

  api:
    build: ./api
    restart: unless-stopped
    environment:
      - MONGO_URL=${MONGO_URL:-mongodb://mongo:27017/pinsaar}
      - REDIS_URL=${REDIS_URL:-redis://redis:6379}
      - ADMIN_TOKEN=${ADMIN_TOKEN:-dev-secret-token}
      - API_PORT=${API_PORT:-3000}
    ports:
      - "3000:3000"
    depends_on:
      - mongo
      - redis

  worker:
    build: ./worker
    restart: unless-stopped
    environment:
      - MONGO_URL=${MONGO_URL:-mongodb://mongo:27017/pinsaar}
    depends_on:
      - mongo

  sink:
    build: ./sink
    restart: unless-stopped
    environment:
      - REDIS_URL=${REDIS_URL:-redis://redis:6379}
      - SINK_PORT=${SINK_PORT:-5000}
      - SINK_ALWAYS_FAIL=${SINK_ALWAYS_FAIL:-false}
    ports:
      - "5000:5000"
    depends_on:
      - redis
